using UnityEngine;
using UnityEngine.InputSystem;

/// <summary>
/// Handles player input for selecting and placing towers on
/// the spots generated by PlacementSpotGenerator, using a 3D
/// raycast from the mouse cursor.
/// </summary>
public class TowerPlacementManager : MonoBehaviour
{
    [SerializeField] private LayerMask placementSpotLayer;
    [SerializeField] private Camera mainCamera;
    [SerializeField] private float maxRaycastDistance = 500f;

    private GameObject selectedTowerPrefab;
    private PlacementSpot currentHoverSpot;

    private void Awake()
    {
        if (mainCamera == null)
            mainCamera = Camera.main;
    }

    /// <summary>Call this from your UI (e.g. a tower-select button) with the tower prefab to build.</summary>
    public void SelectTowerToBuild(GameObject towerPrefab)
    {
        selectedTowerPrefab = towerPrefab;
    }

    public void CancelSelection()
    {
        selectedTowerPrefab = null;

        if (currentHoverSpot != null)
        {
            currentHoverSpot.SetHover(false);
            currentHoverSpot = null;
        }
    }

    private void Update()
    {
        if (selectedTowerPrefab == null)
            return;

        PlacementSpot spotUnderCursor = GetSpotUnderCursor();

        if (spotUnderCursor != currentHoverSpot)
        {
            if (currentHoverSpot != null)
                currentHoverSpot.SetHover(false);

            currentHoverSpot = spotUnderCursor;

            if (currentHoverSpot != null)
                currentHoverSpot.SetHover(true);
        }

        if (Mouse.current != null && Mouse.current.leftButton.wasPressedThisFrame && currentHoverSpot != null)
        {
            TryBuildOn(currentHoverSpot);
        }

        if (Mouse.current != null && Mouse.current.rightButton.wasPressedThisFrame)
        {
            CancelSelection();
        }
    }

    private PlacementSpot GetSpotUnderCursor()
    {
        if (Mouse.current == null)
            return null;

        Ray ray = mainCamera.ScreenPointToRay(Mouse.current.position.ReadValue());

        if (Physics.Raycast(ray, out RaycastHit hit, maxRaycastDistance, placementSpotLayer))
        {
            return hit.collider.GetComponentInParent<PlacementSpot>();
        }

        return null;
    }

    private void TryBuildOn(PlacementSpot spot)
    {
        if (spot.TryPlaceTower(selectedTowerPrefab, out GameObject tower))
        {
            selectedTowerPrefab = null;
            spot.SetHover(false);
            currentHoverSpot = null;
        }
        else
        {
            Debug.Log("That spot is already occupied.");
        }
    }
}